### ISSUE TITLE
Font control settings

### ISSUE THREAD

**Issue by AlexChalk** [RRethy/base16-nvim#93]
Would you accept a PR that added some of this sort of functionality: https://github.com/ellisonleao/gruvbox.nvim?tab=readme-ov-file#configuration? 

e.g. I'd appreciate the ability to disable italicization.

**Comment by RRethy** [comment]
I'd be open to a PR for that. The logic should be contained to the M.highlight function and not alongside the highlight definitions themselves.

**Comment by AlexChalk** [comment]
Thanks! I definitely opened this too early (I don't have time in the near future), so I'm closing the issue and will reopen if I get to it.

**Comment by AlexChalk** [comment]
The plugin I linked to hardlinks the parameters to the highlight groups, e.g. `Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds }`.

If I confine the logic to the highlight function, I can probably cleanly remove all italics by turning it into a closure and passing the `config`:
```
M.highlight = function(config)
  return setmetatable({}, {
    __newindex = function(_, hlgroup, args)
      if config.italic == false and args.gui == "italic" then 
        args.gui == "none" 
      end
```
However, for more fine-grained control over italics (e.g. `config.italic.folds`), this approach would end up reproducing the highlight group logic on a case-by-case basis anyway, which I don't think you want.
