### ISSUE TITLE
Colors not displaying

### ISSUE THREAD

**Issue by casey** [RRethy/base16-nvim#94]
Thanks for writing this plugin!

I'm trying to migrate from `chriskempson/base16-vim`, but I can't get colors to display.

I have:

```
Plug 'RRethy/base16-nvim'
```

And:

```
colorscheme base16-seti
```

In my vimrc.

Here's what it looks like with no colorscheme set:

<img width="853" alt="no colorscheme" src="https://github.com/RRethy/base16-nvim/assets/1945/2954195a-9736-49ce-b898-c54df9406c11">

And here's what it looks like with `colorscheme base16-seti`:

<img width="853" alt="colorscheme base16-seti" src="https://github.com/RRethy/base16-nvim/assets/1945/5d7eceb8-a4ff-44d8-8cd9-2b50cd2ec2b6">

Any idea what I'm doing wrong?

**Comment by RRethy** [comment]
Try `set termguicolors`.

**Comment by casey** [comment]
Thanks, that fixed it!
