### ISSUE TITLE
Split colors are too bright

### ISSUE THREAD

**Issue by Freemason-12** [RRethy/base16-nvim#97]
Whenever I use a rather dark color scheme (Like tomorrow night), split colors are almost always white, and fr most other dark colorschemes this is true as well
is it possible to add functionality which will allow us to use colors given by base16 colorscheme to color some areas like this differently?

**Comment by RRethy** [comment]
I don't know what you mean by split colors.

You can however supply any colors you want using `require('base16-colorscheme').setup` or you can override specific highlight groups directly after loading the colorscheme with the builtin `:highlight <hlgroup>`.

**Comment by Freemason-12** [comment]
![20240425_10h10m08s_grim](https://github.com/RRethy/base16-nvim/assets/97738675/0e8b21c2-a985-442c-a271-e20eeb2d0260)
I mean colors which signify borders of each neovim window when making any kind of split
