### ISSUE TITLE
Better contract when cursorline is enabled, and current line a comment line

### ISSUE THREAD

**Issue by WindSoilder** [RRethy/base16-nvim#98]
Hi, thank you for the good theme!  I love using base16-gruvbox-dark-hard.

But sometimes I found it's hard to read comment when I enabled cursorline:
```lua
vim.opt.cursorline = true
```
And here is screenshot
![image](https://github.com/RRethy/base16-nvim/assets/22256154/fa5744f3-5461-4801-863a-ed61486c99f3)

I think it would be good to make the current line readable

**Comment by RRethy** [comment]
The hlgroups are done using the same named color across all themes, as such some themes will have undesirable colors. Changing this would need a change across all themes which isn't great.

Instead, I'd recommend overriding that color yourself. Add a line like this to your init.lua:

```lua
vim.api.nvim_set_hl(0, 'CursorLine', {bg=require('base16-colorscheme').colors.base02})
```

**Note**: You'll want to change the bg color to fit what you want.
